### ISSUE TITLE
Should delta be a property of the PurePursuitController class?

### ISSUE THREAD

**Issue by matangilad** [Adi-Levy/TechAVSFControl#1]
Since `delta` is only being computed as a service for whoever uses the class of the controller and not an inherit property of the controller maybe it shouldn't be a property of the class. Is there a reason to store it nevertheless?

https://github.com/Adi-Levy/TechAVSFControl/blob/b9c83314b64c1a96c3f48e1099ca677b5c88e82b/PurePursuit/SimpleControllerInterface.py#L42-L43

**Comment by Adi-Levy** [comment]
Since it is being returned as it is calculated I guess not. the reason it was this way is an earlier thought I had of how to implement the controller that didn't work well when I tried to put it together.
Thanks for the input will address this now.
